local Remap = require("jw.keymap")
local nnoremap = Remap.nnoremap
local dropdownTheme = require('telescope.themes').get_dropdown

nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<Leader>pf", function()
    require('telescope.builtin').find_files()
end)

nnoremap("<leader>tt", function()
    require('telescope.builtin').live_grep()
end)

nnoremap("<leader>pw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>pb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>vh", function()
    require('telescope.builtin').help_tags()
end)

nnoremap("<leader>vrc", function()
    require('jw.telescope').search_dotfiles()
end)
nnoremap("<leader>gb", function()
    require('jw.telescope').git_branches(dropdownTheme())
end)
nnoremap("<leader>gw", function()
    require('telescope').extensions.git_worktree.git_worktrees(dropdownTheme())
end)
nnoremap("<leader>gcw", function()
    require('telescope').extensions.git_worktree.create_git_worktree(dropdownTheme())
end)
nnoremap("<leader>gs", function()
    require('telescope.builtin').git_status(dropdownTheme())
end)
-- nnoremap("<leader>td", function()
--     require('jw.telescope').dev()
-- end)
